### ISSUE TITLE
SQL Server transport v3: Upgrade guide

### ISSUE THREAD

**Issue by weralabaj** [Particular/docs.particular.net#1195]
Task force: @tmasternak @weralabaj @justabitofcode @mauroservienti

Plan of attack:
- [x] Clean up multi-db doco and snippets
- [x] Configuration api changes for multi-schema
- [x] Configuration api chagnes for providing custom connection string
- [x] ~~Changes in multi-db support~~ (will be handled by https://github.com/Particular/docs.particular.net/issues/1103)
- [ ]  ~~Document new shutdown timeout behavior for SQL Particular/NServiceBus.Host#51~~ (that was moved to https://github.com/Particular/docs.particular.net/issues/1167)
- [ ]  ~~Document new shutdown timeout behavior for MSMQ~~ (that was moved to https://github.com/Particular/docs.particular.net/issues/1167)
- [x] Mention that transaction settings are configured on the transport level.
- [x] How new transaction modes translate to previous options
- [x] Circuit Breaker - removed methods.
Related to https://github.com/Particular/NServiceBus.SqlServer/issues/100

http://docs.particular.net/nservicebus/upgrades/5to6

**Comment by MarcinHoppe** [comment]
You might also want to mention that transaction settings (mode, isolation level, and timeout) are configured on the transport level and this also includes the SQL transport.

**Comment by tmasternak** [comment]
We should also document:
 * methods around CircuitBreaker that have been removed
 * new transaction modes and how they translate to previous options

**Comment by weralabaj** [comment]
I'm starting work on this

**Comment by weralabaj** [comment]
BTW what does " Document new shutdown timeout behavior for MSMQ" do here?!

**Comment by weralabaj** [comment]
I'll need some help with the shutdown behaviour. @tmasternak you know what are the changes in both MSMQ and Sql?

**Comment by weralabaj** [comment]
@mikeminutillo or @SimonCropp Don't want to self-merge, another review from native would also be useful. Have a look :)

**Comment by indualagarsamy** [comment]
@weralabaj - I've provided my suggestions to the doco changes.

**Comment by mikeminutillo** [comment]
As the associated PR has been merged, is this issue done as well? Or is there more to do?

**Comment by tmasternak** [comment]
Yep. This one is done.
