### ISSUE TITLE
Create a sample on how to send audit messages using a different transport

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/docs.particular.net#6906]
Some transports used in Azure, i.e. Azure Service Bus (premium) and SQL Server, incur very significant per-message costs. Enabling the audit feature effectively doubles the number of messages that need to be pushed by the system. That makes out Platform non cost-effective.

To mitigate that problem, audit messages can be sent to ServiceControl audit instance using a lower cost channel, e.g. Azure Storage Queues.

### Task

The task is to build a sample that contains pipeline behaviors and sending components required to send audit messages via Azure Storage Queues.

#### Limitations

Azure Storage Queues imposes limit on message size. In the interest of time, the sample can make it explicit (via a warning) or, if time permits, contain logic that only offloads messages that fit in the size limit.

### Plan of Action
- [x] Write a sample https://github.com/Particular/docs.particular.net/pull/7160
- [x] Setup SC and SP with 2 different transports and test the sample
- [x] Get a review of the sample
- [x] Add docker composer to the sample
- [x] Get a final review and publish
- [x] Update internal docs in relation to the sample being affected by tight coupling between the audit and error instance.

**Comment by jpalac** [comment]
## 📝 Status update


<details>

<summary>Status icons legend</summary>

- ✅ completed
- ⌛ in-progress
- ⏸️ was paused to progress more relevant work
- ⏯️ was resumed 
- 🛑 is temporarily blocked
- ❌ not yet started
- 🗑️ will not be done (add reason)

</details>

### Progress made



- ⌛ Started working on the sample https://github.com/Particular/docs.particular.net/pull/7160

### 📅 What to expect



- Continue working on the sample

### 🧑‍🤝‍🧑 For the squad



N/A

Next status update planned: 2025-05-30


- [x] The plan of action or project board is up-to-date as of this status update


<sup>[📝](https://github.com/Particular/StaffSuccess/blob/master/github/saved-reply-templates.md#status-update) [guidelines](https://github.com/Particular/StaffSuccess/blob/master/guidelines/facilitation.md#providing-status-updates) version 2025-05-08</sup>

**Comment by jpalac** [comment]
## 📝 Status update


<details>

<summary>Status icons legend</summary>

- ✅ completed
- ⌛ in-progress
- ⏸️ was paused to progress more relevant work
- ⏯️ was resumed 
- 🛑 is temporarily blocked
- ❌ not yet started
- 🗑️ will not be done (add reason)

</details>

### Progress made



- ✅Continue working on the sample
- ✅Setup SC and SP with 2 different transports and test the sample
- ✅Summarised our findings in issues faced
- ⌛Ask for a review

### 📅 What to expect



- Incorporate feedback and decide on next best action

### 🧑‍🤝‍🧑 For the squad



N/A

Next status update planned: 2025-06-02


- [x] The plan of action or project board is up-to-date as of this status update


<sup>[📝](https://github.com/Particular/StaffSuccess/blob/master/github/saved-reply-templates.md#status-update) [guidelines](https://github.com/Particular/StaffSuccess/blob/master/guidelines/facilitation.md#providing-status-updates) version 2025-05-08</sup>

**Comment by jpalac** [comment]
## 📝 Status update


<details>

<summary>Status icons legend</summary>

- ✅ completed
- ⌛ in-progress
- ⏸️ was paused to progress more relevant work
- ⏯️ was resumed 
- 🛑 is temporarily blocked
- ❌ not yet started
- 🗑️ will not be done (add reason)

</details>

### Progress made



- ❌ Incorporate feedback and decide on next best action - waiting on a review

### 📅 What to expect



- Incorporate feedback and decide on next best action

### 🧑‍🤝‍🧑 For the squad



N/A

Next status update planned: 2025-06-06


- [x] The plan of action or project board is up-to-date as of this status update


<sup>[📝](https://github.com/Particular/StaffSuccess/blob/master/github/saved-reply-templates.md#status-update) [guidelines](https://github.com/Particular/StaffSuccess/blob/master/guidelines/facilitation.md#providing-status-updates) version 2025-05-08</sup>

**Comment by SzymonPobiega** [comment]
> we could detect and properly describe the situation

I can try to fame a small task/improvement issue for SP to show some sort of widget around a message for which we have both a failed and a succeeded copy indicating that the failure means that not all outgoing message have been dispatched.

**Comment by mikeminutillo** [comment]
> By replacing the connector with a terminator, the sample bypasses the Outbox entirely (is that assumption correct?)
> The outbox pipeline is [executed in the incoming physical](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Audit/InvokeAuditPipelineBehavior.cs) stage i.e. after the message has been processed but before the outbox record has been committed

Yes. The audit message is dispatched before the outbox record is updated or dispatched, so it is not involved.

> Based on ☝ , if the outbox commit or dispatch fails, the audit message will be re-generated
> Also based on ☝ , if the outbox commit or dispatch fails, the audit message will have been delivered to the audit queue (signaling a successful attempt at processing a message)

Yes. If the message is processed again, then we will have duplicate audit messages in the audit queue with different processing times. I have not checked to see how gracefully ServiceControl handles this. It should create two copies of the audit record which have the same [unique IDs](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Audit.Persistence/Infrastructure/TransportMessageExtensions.cs#L39-L44) but different [processing IDs](http://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Audit.Persistence/Infrastructure/TransportMessageExtensions.cs#L46C36-L57).

> Also based on ☝ similar thing can happen without the sample if the failure happens after the outbox dispatch (during incoming message ACK process)

Yes, but....

This wouldn't happen if the transport is running in sends-atomic-with-recieve. This is because the outgoing audit message would be sent in the receive transaction.

If the outbox is enabled, and this were not an audit message, then the outbox on the other end would deduplicate the message. 

ServiceControl cannot be configured to use the outbox and contains it's own deduplication logic as it has to deal with multiple copies of the same event that have been processed by different endpoints.

If this happened after the outbox record was committed and we had multiple outbox dispatches, the duplicates would have the same unique-id AND the same processing-id. Those are based on headers which are stored in the outbox record.

**Comment by abparticular** [comment]
>Audit should IMO be understood as audit of a processing attempt.

Our [documentation states otherwise](https://docs.particular.net/nservicebus/operations/auditing#how-it-works), in bold.

**Comment by jpalac** [comment]
## 📝 Status update


<details>

<summary>Status icons legend</summary>

- ✅ completed
- ⌛ in-progress
- ⏸️ was paused to progress more relevant work
- ⏯️ was resumed 
- 🛑 is temporarily blocked
- ❌ not yet started
- 🗑️ will not be done (add reason)

</details>

### Progress made



- ✅Get a final review and publish
- ✅Update internal docs in relation to the sample being affected by tight coupling between the audit and error instance.
  - https://github.com/Particular/Platform/pull/1156


### 📅 What to expect



- This is done

### 🧑‍🤝‍🧑 For the squad



N/A

Next status update planned: NONE


- [x] The plan of action or project board is up-to-date as of this status update


<sup>[📝](https://github.com/Particular/StaffSuccess/blob/master/github/saved-reply-templates.md#status-update) [guidelines](https://github.com/Particular/StaffSuccess/blob/master/guidelines/facilitation.md#providing-status-updates) version 2025-05-08</sup>

**Comment by jpalac** [comment]
## 🚀 This is done



### ✔ What has been done



- Investigated sending pipeline and audit behaviour for options and blockers 
- Created sample that contains pipeline behaviors and sending components required to send audit messages via Azure Storage Queues. 
- Updated internal docs  in relation to the sample being affected by tight coupling between the audit and error instance.

### 🏺 Artifacts



- [Sample PR](https://github.com/Particular/docs.particular.net/pull/7160)
- [Sample on docs website](https://docs.particular.net/samples/azure/custom-audit-transport/)
- [Internal docs update](https://github.com/Particular/Platform/pull/1156)

### 🏠 Town hall notes



Some transports used in Azure, i.e. Azure Service Bus (premium) and SQL Server, incur very significant per-message costs. Enabling the audit feature effectively doubles the number of messages that need to be pushed by the system. That makes out Platform non cost-effective.

To mitigate that problem, audit messages can be sent to ServiceControl audit instance using a lower cost channel, e.g. Azure Storage Queues. A [sample](https://docs.particular.net/samples/azure/custom-audit-transport/) has been created to demonstrate how this can be achieved when using Azure Service Bus as the main transport (for endpoints and ServiceControl error instance) and Azure Storage Queues as the audit instance transport.


<sup>[📝](https://github.com/Particular/StaffSuccess/blob/master/github/saved-reply-templates.md#closing-issues) [guidelines](https://github.com/Particular/StaffSuccess/blob/master/guidelines/facilitation.md#closing-issues) version 2025-01-09</sup>
